# Generated by Django 6.1.1 on 2026-09-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер замовлення')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('delivery_method', models.CharField(choices=[('nova_poshta', 'Нова пошта'), ('ukr_poshta', 'Укрпошта'), ('pickup', 'Самовивіз')], max_length=30, verbose_name='Доставка')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Відділення / адреса')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка при отриманні'), ('card', 'Оплата карткою'), ('online', 'Онлайн-оплата')], max_length=30, verbose_name='Оплата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('shipped', 'Відправлено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Остання зміна')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна на момент покупки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
        ),
    ]
