# Generated by Django 6.1.1 on 2026-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('computers', "Комп'ютери"), ('phones', 'Телефони'), ('laptops', 'Ноутбуки'), ('accessories', 'Аксесуари')], max_length=100, verbose_name='Категорія'),
        ),
    ]
