# Generated by Django 6.1.1 on 2026-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('category', models.CharField(choices=[('computers', "Комп'ютери"), ('phones', 'Телефони'), ('laptops', 'Ноутбуки'), ('accessories', 'Аксесуари'), ('gaming', 'Ігрова техніка'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Категорія')),
                ('condition', models.CharField(choices=[('new', 'Новий'), ('used', 'Вживаний')], default='used', max_length=20, verbose_name='Стан')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Фото')),
                ('seller_name', models.CharField(max_length=100, verbose_name='Продавець')),
                ('status', models.CharField(choices=[('active', 'Активне'), ('sold', 'Продано'), ('closed', 'Закрито')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ['-created_at'],
            },
        ),
    ]
